name: MC-PixelartPlugin
main: com.github.xsillusx.mcpixelart.MCPixelArt
version: 0.1
api-version: 1.13
commands:
  pixelart:
    description: Generates a pixelart from a image url
    usage: /pixelart <url> <width> <height>